import { Button, VerticalBox, HorizontalBox, Spinner } from "std-widgets.slint";

component TextButton inherits Rectangle {
    in-out property text <=> txt.text;
    in-out property font-size <=> txt.font-size;
    in-out property enabled <=> touch.enabled;
    callback clicked <=> touch.clicked;
    border-radius: root.height / 4;
    border-width: 1px;
    border-color: root.background.darker(25%);
    background: touch.pressed ? #6b8282 : touch.has-hover ? #6c616c : #456;
    min-height: txt.preferred-height + 20px;
    // min-height: txt.preferred-height + 20px;
    min-width: txt.preferred-width * 2;
    txt := Text {
        x: (parent.width - self.width) / 2 + (touch.pressed ? 2px : 0);
        y: (parent.height - self.height) / 2 + (touch.pressed ? 1px : 0) + 2px;
        color: touch.pressed ? #fff : #eee;
        font-size: 32px;
    }

    touch := TouchArea { }
}

component ImageButton inherits Rectangle {
    in-out property source <=> img.source;
    in-out property enabled <=> touch.enabled;
    callback clicked <=> touch.clicked;
    border-radius: root.height / 4;
    border-width: 1px;
    border-color: root.background.darker(25%);
    background: touch.pressed ? #6b8282 : touch.has-hover ? #6c616c : #456;
    // height: img.preferred-height * 1.2;
    min-width: img.preferred-width + 20px;
    img := Image {
        x: (parent.width - self.width) / 2 + (touch.pressed ? 2px : 0);
        y: (parent.height - self.height) / 2 + (touch.pressed ? 1px : 0) + 2px;
        height: parent.height - 20px;
    }

    touch := TouchArea { }
}

export component AppWindow inherits Window {
    title: "Math Quiz";
    icon: @image-url("math-quiz.png");
    min-width: 500px;
    min-height: 500px;

    in-out property <string> id;
    in-out property question <=> question-box.text;
    in-out property answer <=> answer-box.text;
    in-out property <bool> number-enabled;
    in-out property correct-overlay-visible <=> correct-overlay.visible;
    in-out property incorrect-overlay-visible <=> incorrect-overlay.visible;
    in-out property loading-overlay-visible <=> loading-overlay.visible;

    callback submit-clicked();
    callback num-clicked(int);
    callback backspace-clicked();

    loading-overlay := Spinner {
        height: self.width;
        width: 100px;
        visible: false;
        indeterminate: true;
        z: 20;
    }

    correct-overlay := Image {
        height: self.width;
        width: 100%;
        source: @image-url("../../frontend/public/check-mark.svg");
        visible: false;
        z: 10;
    }

    incorrect-overlay := Image {
        height: self.width;
        width: 100%;
        source: @image-url("../../frontend/public/wrong-mark.svg");
        visible: false;
        z: 10;
    }

    VerticalBox {
        z: 0;
        question-box := Text {
            text: "123 x 456";
            font-size: 64px;
            font-family: "Monospace";
            height: 80px;
        }

        answer-box := Text {
            text: "8765";
            font-size: 64px;
            font-family: "Monospace";
            height: 80px;
        }

        Rectangle {
            min-height: 10px;
        }

        HorizontalBox {
            height: 80px;
            TextButton {
                text: "1";
                enabled: number-enabled;
                clicked => {
                    root.num-clicked(1);
                }
            }

            TextButton {
                text: "2";
                enabled: number-enabled;
                clicked => {
                    root.num-clicked(2);
                }
            }

            TextButton {
                text: "3";
                enabled: number-enabled;
                clicked => {
                    root.num-clicked(3);
                }
            }

            TextButton {
                text: "4";
                enabled: number-enabled;
                clicked => {
                    root.num-clicked(4);
                }
            }

            TextButton {
                text: "5";
                enabled: number-enabled;
                clicked => {
                    root.num-clicked(5);
                }
            }
        }

        HorizontalBox {
            height: 80px;
            TextButton {
                text: "6";
                enabled: number-enabled;
                clicked => {
                    root.num-clicked(6);
                }
            }

            TextButton {
                text: "7";
                enabled: number-enabled;
                clicked => {
                    root.num-clicked(7);
                }
            }

            TextButton {
                text: "8";
                enabled: number-enabled;
                clicked => {
                    root.num-clicked(8);
                }
            }

            TextButton {
                text: "9";
                enabled: number-enabled;
                clicked => {
                    root.num-clicked(9);
                }
            }

            TextButton {
                text: "0";
                enabled: number-enabled;
                clicked => {
                    root.num-clicked(0);
                }
            }
        }

        HorizontalBox {
            height: 100px;
            ImageButton {
                source: @image-url("backspace.svg");
                background: #950000;
                enabled: answer-box.text != "";
                height: 80px;
                clicked => {
                    root.backspace-clicked();
                }
            }

            ImageButton {
                source: @image-url("../../frontend/public/check-mark.svg");
                background: #0e620e;
                enabled: answer-box.text != "";
                height: 80px;
                clicked => {
                    root.submit-clicked();
                }
            }
        }
    }
}
