import { Button, VerticalBox, HorizontalBox, Spinner, TabWidget, StandardTableView } from "std-widgets.slint";
import {Quiz} from "quiz.slint";

export component AppWindow inherits Window {
    title: "计算练习";
    icon: @image-url("math-quiz.png");
    in-out property id <=> quiz.id;
    in-out property question <=> quiz.question;
    in-out property answer <=> quiz.answer;
    in-out property number-enabled <=> quiz.number-enabled;
    in-out property correct-overlay-visible <=> quiz.correct-overlay-visible;
    in-out property incorrect-overlay-visible <=> quiz.incorrect-overlay-visible;
    in-out property loading-overlay-visible <=> quiz.loading-overlay-visible;
    callback submit-clicked();
    callback num-clicked(int);
    callback backspace-clicked();
    TabWidget {
        z: 0;
        Tab {
            title: "练习";
            quiz := Quiz {
                submit-clicked => {
                    submit-clicked()
                }
                num-clicked(n) => {
                    num-clicked(n)
                }
                backspace-clicked => {
                    backspace-clicked()
                }
            }
        }

        Tab {
            title: "成绩单";
            score-sheet := StandardTableView {
                width: 100%;
                height: 100%;
                columns: [
                    { title: "日期" },
                    { title: "总数" },
                    { title: "正确" },
                    { title: "得分" },
                ];
                rows: [
                    [
                        { text: "Item 1" },
                        { text: "Item 2" },
                        { text: "Item 3" },
                        { text: "Item 4" },
                    ],
                    [
                        { text: "Item 1" },
                        { text: "Item 2" },
                        { text: "Item 3" },
                        { text: "Item 4" },
                    ],
                    [
                        { text: "Item 1" },
                        { text: "Item 2" },
                        { text: "Item 3" },
                        { text: "Item 4" },
                    ]
                ];
            }
        }

        Tab {
            title: "错题本";
            mistake-collection := StandardTableView {
                width: 100%;
                height: 100%;
                columns: [
                    { title: "日期" },
                    { title: "题目" },
                    { title: "错误答案" },
                ];
                rows: [
                    [
                        { text: "Item 1" },
                        { text: "Item 2" },
                        { text: "Item 3" },
                    ],
                    [
                        { text: "Item 1" },
                        { text: "Item 2" },
                        { text: "Item 3" },
                    ],
                    [
                        { text: "Item 1" },
                        { text: "Item 2" },
                        { text: "Item 3" },
                    ]
                ];
            }
        }
    }
}
