import { Button, VerticalBox, HorizontalBox, Spinner, TabWidget, StandardTableView } from "std-widgets.slint";
import {Quiz} from "quiz.slint";

export component AppWindow inherits Window {
    title: "计算练习";
    icon: @image-url("math-quiz.png");
    in-out property loading-overlay-visible <=> loading-overlay.visible;
    in-out property id <=> quiz.id;
    in-out property question <=> quiz.question;
    in-out property answer <=> quiz.answer;
    in-out property number-enabled <=> quiz.number-enabled;
    in-out property correct-overlay-visible <=> quiz.correct-overlay-visible;
    in-out property incorrect-overlay-visible <=> quiz.incorrect-overlay-visible;
    in property <[{date: string, total: string, correct: string, score: string}]> scores;
    callback submit-clicked <=> quiz.submit-clicked;
    callback num-clicked <=> quiz.num-clicked;
    callback backspace-clicked <=> quiz.backspace-clicked;
    callback tab-changed(int);
    // Global overlay for loading spinner
    loading-overlay := Spinner {
        height: self.width;
        width: 100px;
        visible: false;
        indeterminate: true;
        z: 20;
    }

    TabWidget {
        z: 0;
        // This is not yet officially supported.
        // Needs `SLINT_ENABLE_EXPERIMENTAL_FEATURES` set to `1` in `.cargo/config.toml`
        changed current-index => {
            tab-changed(self.current-index);
        }
        Tab {
            title: "练习";
            quiz := Quiz {
                width: 100%;
                height: 100%;
            }
        }

        Tab {
            title: "成绩单";
            score-sheet := StandardTableView {
                width: 100%;
                height: 100%;
                columns: [
                    { title: "日期" },
                    { title: "总数" },
                    { title: "正确" },
                    { title: "得分" },
                ];
                rows: [];
            }
        }

        Tab {
            title: "错题本";
            mistake-collection := StandardTableView {
                width: 100%;
                height: 100%;
                columns: [
                    { title: "日期" },
                    { title: "题目" },
                    { title: "错误答案" },
                ];
                rows: [
                    [
                        { text: "Item 1" },
                        { text: "Item 2" },
                        { text: "Item 3" },
                    ],
                    [
                        { text: "Item 1" },
                        { text: "Item 2" },
                        { text: "Item 3" },
                    ],
                    [
                        { text: "Item 1" },
                        { text: "Item 2" },
                        { text: "Item 3" },
                    ]
                ];
            }
        }
    }
}
